"""Add priority field to SiteAlias

Revision ID: 0eb8618a233d
Revises: f8b5d361bc21
Create Date: 2017-09-17 19:21:44.162762

"""

# revision identifiers, used by Alembic.
revision = '0eb8618a233d'
down_revision = 'f8b5d361bc21'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitealias', sa.Column('priority', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitealias', 'priority')
    ### end Alembic commands ###
