"""Add HTTP host and port overrides

Revision ID: 29073686c35f
Revises: 48e7daaf3dfa
Create Date: 2017-02-20 20:09:44.223579

"""

# revision identifiers, used by Alembic.
revision = '29073686c35f'
down_revision = '48e7daaf3dfa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('http_override_host', sa.String(), nullable=True))
    op.add_column('site', sa.Column('http_override_port', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'http_override_port')
    op.drop_column('site', 'http_override_host')
    ### end Alembic commands ###
