"""Add full contents to mastertracefile

Revision ID: 3e878eec9b56
Revises: 5ed37dd9e103
Create Date: 2017-02-21 14:16:10.052263

"""

# revision identifiers, used by Alembic.
revision = '3e878eec9b56'
down_revision = '5ed37dd9e103'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastertrace', sa.Column('full', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mastertrace', 'full')
    ### end Alembic commands ###
