"""create checkoverview table

Revision ID: 516c878785c1
Revises: ae076014ddd0
Create Date: 2017-08-29 06:40:10.523125

"""

# revision identifiers, used by Alembic.
revision = '516c878785c1'
down_revision = 'ae076014ddd0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkoverview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('checkrun_id', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('version', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['checkrun_id'], ['checkrun.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkoverview_checkrun_id'), 'checkoverview', ['checkrun_id'], unique=False)
    op.create_index(op.f('ix_checkoverview_site_id'), 'checkoverview', ['site_id'], unique=False)
    op.create_index(op.f('ix_sitetrace_trace_timestamp'), 'sitetrace', ['trace_timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sitetrace_trace_timestamp'), table_name='sitetrace')
    op.drop_index(op.f('ix_checkoverview_site_id'), table_name='checkoverview')
    op.drop_index(op.f('ix_checkoverview_checkrun_id'), table_name='checkoverview')
    op.drop_table('checkoverview')
    ### end Alembic commands ###
