"""Add a bunch of indexes

Revision ID: 5ed37dd9e103
Revises: 29073686c35f
Create Date: 2017-02-21 10:17:55.656699

"""

# revision identifiers, used by Alembic.
revision = '5ed37dd9e103'
down_revision = '29073686c35f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mastertrace_checkrun_id'), 'mastertrace', ['checkrun_id'], unique=False)
    op.create_index(op.f('ix_mastertrace_site_id'), 'mastertrace', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_origin_id'), 'site', ['origin_id'], unique=False)
    op.create_index(op.f('ix_sitetrace_checkrun_id'), 'sitetrace', ['checkrun_id'], unique=False)
    op.create_index(op.f('ix_sitetrace_site_id'), 'sitetrace', ['site_id'], unique=False)
    op.create_index(op.f('ix_traceset_checkrun_id'), 'traceset', ['checkrun_id'], unique=False)
    op.create_index(op.f('ix_traceset_site_id'), 'traceset', ['site_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traceset_site_id'), table_name='traceset')
    op.drop_index(op.f('ix_traceset_checkrun_id'), table_name='traceset')
    op.drop_index(op.f('ix_sitetrace_site_id'), table_name='sitetrace')
    op.drop_index(op.f('ix_sitetrace_checkrun_id'), table_name='sitetrace')
    op.drop_index(op.f('ix_site_origin_id'), table_name='site')
    op.drop_index(op.f('ix_mastertrace_site_id'), table_name='mastertrace')
    op.drop_index(op.f('ix_mastertrace_checkrun_id'), table_name='mastertrace')
    ### end Alembic commands ###
