"""index on checkrun timestamp

Revision ID: ae076014ddd0
Revises: 3e878eec9b56
Create Date: 2017-02-21 20:04:54.192768

"""

# revision identifiers, used by Alembic.
revision = 'ae076014ddd0'
down_revision = '3e878eec9b56'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checkrun_timestamp'), 'checkrun', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkrun_timestamp'), table_name='checkrun')
    ### end Alembic commands ###
