"""Add a SiteAlias

Revision ID: e28072a46d54
Revises: 4a549ee09bcb
Create Date: 2017-09-02 22:02:39.854867

"""

# revision identifiers, used by Alembic.
revision = 'e28072a46d54'
down_revision = '4a549ee09bcb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitealias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitealias_site_id'), 'sitealias', ['site_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sitealias_site_id'), table_name='sitealias')
    op.drop_table('sitealias')
    ### end Alembic commands ###
