"""Store Archive-Update-in-Progress and -Required flags

Revision ID: f8b5d361bc21
Revises: ce3bfa759e8d
Create Date: 2017-09-16 20:03:04.881605

"""

# revision identifiers, used by Alembic.
revision = 'f8b5d361bc21'
down_revision = 'ce3bfa759e8d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitetrace', sa.Column('archive_update_in_progress', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sitetrace', sa.Column('archive_update_required', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitetrace', 'archive_update_required')
    op.drop_column('sitetrace', 'archive_update_in_progress')
    ### end Alembic commands ###
